name: copy-pdf

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
      # - "443:443"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ~/Apps/docker_apps/copy-pdf/caddy:/etc/caddy
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - copy-pdf

  copy-pdf:
    image: schneiderstep/copy-pdf:test
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - COPY_PDF_USER_STORE=/api_users/users
    volumes:
      - ~/Apps/docker_apps/copy-pdf/users:/api_users
      - ~/Apps/docker_apps/copy-pdf/logs:/var/log/copy_pdf

volumes:
  caddy-data:
  caddy-config:
  
